name: requested
on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install dev dependencies
        run: sudo apt-get install libasound2-dev libjack-jackd2-dev libudev-dev

      - name: Build
        run: cargo build

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Ninja for building shaderc
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        run: cargo build
